### ISSUE TITLE
Vue project deploy

### ISSUE THREAD

**Issue by nagisa1993** [PaddyMurphy/riverplan#1]
Hi! I saw your vue-cli project was successfully deployed on Github. I have a vue-cli project which I want to deploy on Github too, but I tried so many times, every time I opened the page, it was blank. I don't know what's wrong with my code? But it works well under localhost. I changed the config index.js but it didn't work. Could you please help me? my project [here](https://github.com/nagisa1993/Portfolio), blank page [here](https://nagisa1993.github.io/Portfolio/). Thank you so much for your time!

**Comment by PaddyMurphy** [comment]
Hey Haiyue,

In your config/index.js change your index and assetsRoot to ../docs and your assetsPublicPath to ''.

Mine looks like:

`index: path.resolve(__dirname, '../docs/index.html'),  
  assetsRoot: path.resolve(__dirname, '../docs'),  
  assetsSubDirectory: 'static', 
  assetsPublicPath: '',  
`

then under your github Settings > GitHub Pages change your source to your /docs folder.

<img width="331" alt="screen shot 2017-07-17 at 11 49 38 pm" src="https://user-images.githubusercontent.com/699732/28301241-c15c7d3e-6b4a-11e7-86ea-0848b307c4a8.png">

Hope that helps

**Comment by nagisa1993** [comment]
Thanks for your quick reply. I did do so but it didn't work:(
